#Hugo configuration
title = "Test ADS"
baseURL = "https:\/\/ad.test.com"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758904"
subfolder = ""
